// Generated by scripts/sync-abis.mjs from out/HeritRegistry.sol/HeritRegistry.json.
// Do not edit — run `forge build && npm run abi`.

export const heritRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "grantorRegistry",
        "type": "address",
        "internalType": "contract IPermissionedRegistry"
      },
      {
        "name": "gate",
        "type": "address",
        "internalType": "contract AccessControlGate"
      },
      {
        "name": "vault",
        "type": "address",
        "internalType": "contract HeritVault"
      },
      {
        "name": "attestor",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "I_ATTESTOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "I_GATE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract AccessControlGate"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "I_GRANTOR_REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPermissionedRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "I_VAULT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract HeritVault"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_CHECK_IN_INTERVAL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_GRACE_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_HEIRS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_OVERRIDE_TOKENS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_CHECK_IN_INTERVAL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_GRACE_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "checkIn",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "configure",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "checkInInterval",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "graceDuration",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deadlinesOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "graceStartsAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "unlocksAt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultShareOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "estateOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "estate",
        "type": "tuple",
        "internalType": "struct HeritRegistry.Estate",
        "components": [
          {
            "name": "lastCheckIn",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "checkInInterval",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "graceDuration",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum IHeritRegistry.Status"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heirAddressOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heirLabelOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heirSlotsOf",
    "inputs": [
      {
        "name": "heir",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct HeritRegistry.HeirSlot[]",
        "components": [
          {
            "name": "estateId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "heirLabelhash",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heirsOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isAvailable",
    "inputs": [
      {
        "name": "label",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pokeExpiry",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordHeir",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "label",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "heir",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "defaultShareBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setShare",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "shareOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "statusOf",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum IHeritRegistry.Status"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CheckedIn",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EnteredGrace",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EstateConfigured",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "checkInInterval",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "graceDuration",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HeirRecorded",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "heir",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "defaultShareBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ShareSet",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "bps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unlocked",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "at",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "heirCount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "HeritRegistry__EstateNotFound",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__EstateUnlocked",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__HeirNotFound",
    "inputs": [
      {
        "name": "heirLabelhash",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__InvalidTimers",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HeritRegistry__NotActive",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__NotAttestor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HeritRegistry__NotConfigured",
    "inputs": [
      {
        "name": "estateId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__NotGate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HeritRegistry__NotGrantor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HeritRegistry__ShareOverflow",
    "inputs": [
      {
        "name": "totalBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__TooManyHeirs",
    "inputs": [
      {
        "name": "maxHeirs",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__TooManyTokens",
    "inputs": [
      {
        "name": "maxTokens",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HeritRegistry__ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  }
] as const;
