[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "foundry-devops/=lib/foundry-devops/",
    "@ensdomains/contracts-v2/=lib/contracts-v2/contracts/src/",
]

[rpc_endpoints]
sepolia_eth = "${ETH_SEPOLIA_RPC_URL}"
worldchain_sepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
