// Copy ABIs out of Foundry's artifacts and into `lib/contracts/abis/`, plus plain JSON copies in
// `subgraph/abis/` for graph-cli.
//
// The point is that no ABI in this app is written by hand: the contracts are the source, and
// this makes the frontend's copy a build product of `forge build` rather than something that
// drifts. Run it after a build:
//
//   forge build && npm run abi
//
// Zero dependencies on purpose — it is a file copy with a type annotation stapled on.

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "out");
const DEST = join(HERE, "..", "lib", "contracts", "abis");
const SUBGRAPH_DEST = join(HERE, "..", "subgraph", "abis");

/** The contracts the frontend actually calls. Anything else in `out/` is noise. */
const WANTED = [
  "HeritRegistry",
  "HeritVault",
  "AccessControlGate",
  "ClaimManager",
  "LivenessAttestor",
];

const lowerFirst = (s) => s[0].toLowerCase() + s.slice(1);

async function readArtifact(name) {
  const path = join(OUT, `${name}.sol`, `${name}.json`);
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

async function main() {
  try {
    await readdir(OUT);
  } catch {
    console.error(`No artifacts at ${OUT}. Run \`forge build\` from the repo root first.`);
    process.exit(1);
  }

  await mkdir(DEST, { recursive: true });
  await mkdir(SUBGRAPH_DEST, { recursive: true });

  const written = [];
  const missing = [];

  for (const name of WANTED) {
    const artifact = await readArtifact(name);
    if (artifact === null || !Array.isArray(artifact.abi)) {
      missing.push(name);
      continue;
    }

    const file = join(DEST, `${lowerFirst(name)}.abi.ts`);
    const body =
      `// Generated by scripts/sync-abis.mjs from out/${name}.sol/${name}.json.\n` +
      `// Do not edit — run \`forge build && npm run abi\`.\n\n` +
      `export const ${lowerFirst(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

    await writeFile(file, body, "utf8");
    // graph-cli wants the bare ABI array, and names data sources after these files.
    await writeFile(join(SUBGRAPH_DEST, `${name}.json`), `${JSON.stringify(artifact.abi, null, 2)}\n`, "utf8");
    written.push(`${name} (${artifact.abi.length} entries)`);
  }

  for (const name of written) console.log(`wrote ${name}`);
  // Not an error: ClaimManager and LivenessAttestor are still stubs at Checkpoint 8/9.
  if (missing.length > 0) console.log(`skipped, no artifact yet: ${missing.join(", ")}`);
}

await main();
